language: objective-c
node_js:
  - "0.10"
install:
  - npm install
  - (if [ ! -d cordova-lib/cordova-lib ] ; then git clone https://github.com/apla/cordova-lib -b patch-1 ; fi)
  - npm install ./cordova-lib/cordova-lib
  - rm -rf node_modules/cordova/node_modules/cordova-lib
  - (if [ -d app-preferences-app ] ; then rm -rf app-preferences-app ; fi)
  - pwd
  - ls -la
  - ls -la node_modules
  - ls -la node_modules/.bin
  - node_modules/.bin/cordova create app-preferences-app
script:
  - echo running jasmine test
  - cd bin
  - ../node_modules/.bin/jasmine
  - cd ..
  - echo test plugin within cordova app
  - cd app-preferences-app
  - ../node_modules/.bin/cordova platform add ios android
  - ../node_modules/.bin/cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
  - ../node_modules/.bin/cordova prepare
  - echo plugin must be ok without platforms installed
  - ../node_modules/.bin/cordova platform rm android
  - ../node_modules/.bin/cordova prepare
  - ../node_modules/.bin/cordova platform rm ios
  - ../node_modules/.bin/cordova -d platform add android
  - ../node_modules/.bin/cordova platform add ios
  - echo plugin can be uninstalled
  - ../node_modules/.bin/cordova plugin rm cordova-plugin-app-preferences
  - ../node_modules/.bin/cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
  - ../node_modules/.bin/cordova prepare
  - echo plugin must not rewrite existing Settings.bundle generated by external tool
  - rm platforms/ios/Settings.bundle/.me.apla.apppreferences
  - (! ../node_modules/.bin/cordova prepare)
  - touch platforms/ios/Settings.bundle/.me.apla.apppreferences
  - ../node_modules/.bin/cordova prepare
  - echo plugin must cleanup after remove
  - ../node_modules/.bin/cordova plugin rm cordova-plugin-app-preferences
  - (if [ ! -d platforms/ios/Settings.bundle ]; then exit 0 ; fi)
  - ../node_modules/.bin/cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
  - ../node_modules/.bin/cordova prepare
  - echo plugin must not rewrite existing Settings.bundle generated by external tool
  - rm platforms/ios/Settings.bundle/.me.apla.apppreferences
  - ../node_modules/.bin/cordova plugin rm cordova-plugin-app-preferences
  - (if [ -f platforms/ios/Settings.bundle/Root.plist ]; then exit 0 ; fi)
  - ../node_modules/.bin/cordova plugin add https://github.com/apla/me.apla.cordova.app-preferences
  - touch platforms/ios/Settings.bundle/.me.apla.apppreferences
  - ../node_modules/.bin/cordova prepare
after_script:
  - cd ..
  - echo rm -rf node_modules
  - echo rm -rf app-preferences-app


